import argparse
def dataset_optim_args(dataset):
    p = argparse.ArgumentParser()
    if dataset=='BBBP':
        p.add_argument('--dataset', type=str,default='BBBP')
        p.add_argument('--seed', type=int, default=0)
        p.add_argument('--atom_in_dim', type=int, default=37)
        p.add_argument('--bond_in_dim', type=int, default=13)
        p.add_argument('--ss_node_in_dim', type=int, default=50)
        p.add_argument('--ss_edge_in_dim', type=int, default=37)
        p.add_argument('--mol_in_dim', type=int, default=167)
        p.add_argument('--learning_rate', type=int, default=5e-3)
        p.add_argument('--epoch', type=int, default=150,)
        p.add_argument('--batch_size', type=int, default=200)
        p.add_argument('--num_neurons', type=list, default=[512])
        p.add_argument('--input_norm', type=str, default='layer')
        p.add_argument('--drop_rate', type=float, default=0.2)
        p.add_argument('--hid_dim', type=int, default=96)
        p.add_argument('--device', type=str, default='cuda:0')
        p.add_argument('--dist',type=float,default=0.08)
        p.add_argument('--split_ratio',type=list,default=[0.8,0.1,0.1])
        p.add_argument('--folds',type=int,default=10)
        p.add_argument('--n_jobs',type=int,default=40)
        p.add_argument('--resdual',type=bool,default=True)
        p.add_argument('--shuffle',type=bool,default=False)
        p.add_argument('--attention',type=bool,default=True)
        p.add_argument('--step',type=int,default=4)
        p.add_argument('--alpha',type=float,default=0.4)
        p.add_argument('--agg_op',type=str,default='mean')
        p.add_argument('--mol_FP',type=str,default='ss')
    elif dataset=='BACE':
        p.add_argument('--dataset', type=str,default='BACE')
        p.add_argument('--seed', type=int, default=0)
        p.add_argument('--atom_in_dim', type=int, default=37)
        p.add_argument('--bond_in_dim', type=int, default=13)
        p.add_argument('--ss_node_in_dim', type=int, default=50)
        p.add_argument('--ss_edge_in_dim', type=int, default=37)
        p.add_argument('--mol_in_dim', type=int, default=167)
        p.add_argument('--learning_rate', type=int, default=5e-3)
        p.add_argument('--epoch', type=int, default=150)
        p.add_argument('--batch_size', type=int, default=500)
        p.add_argument('--num_neurons', type=list, default=[512])
        p.add_argument('--input_norm', type=str, default='layer')
        p.add_argument('--drop_rate', type=float, default=0.4)
        p.add_argument('--hid_dim', type=int, default=96)
        p.add_argument('--device', type=str, default='cuda:0')
        p.add_argument('--dist',type=float,default=0.01)
        p.add_argument('--split_ratio',type=list,default=[0.8,0.1,0.1])
        p.add_argument('--folds',type=int,default=10)
        p.add_argument('--n_jobs',type=int,default=40)
        p.add_argument('--resdual',type=bool,default=False)
        p.add_argument('--shuffle',type=bool,default=False)
        p.add_argument('--attention',type=bool,default=True)
        p.add_argument('--step',type=int,default=4)
        p.add_argument('--alpha',type=float,default=0.6)
        p.add_argument('--agg_op',type=str,default='max')
        p.add_argument('--mol_FP',type=str,default='ss')
    elif dataset=='SIDER':
        p.add_argument('--dataset', type=str,default='SIDER')
        p.add_argument('--seed', type=int, default=0)
        p.add_argument('--atom_in_dim', type=int, default=37)
        p.add_argument('--bond_in_dim', type=int, default=13)
        p.add_argument('--ss_node_in_dim', type=int, default=50)
        p.add_argument('--ss_edge_in_dim', type=int, default=37)
        p.add_argument('--mol_in_dim', type=int, default=167)
        p.add_argument('--learning_rate', type=int, default=5e-3)
        p.add_argument('--epoch', type=int, default=150)
        p.add_argument('--batch_size', type=int, default=200)
        p.add_argument('--num_neurons', type=list, default=[512])
        p.add_argument('--input_norm', type=str, default='layer')
        p.add_argument('--drop_rate', type=float, default=0.4)
        p.add_argument('--hid_dim', type=int, default=96)
        p.add_argument('--device', type=str, default='cuda:0')
        p.add_argument('--dist',type=float,default=0.08)
        p.add_argument('--split_ratio',type=list,default=[0.8,0.1,0.1])
        p.add_argument('--folds',type=int,default=10)
        p.add_argument('--n_jobs',type=int,default=40)
        p.add_argument('--resdual',type=bool,default=False)
        p.add_argument('--shuffle',type=bool,default=False)
        p.add_argument('--attention',type=bool,default=True)
        p.add_argument('--step',type=int,default=4)
        p.add_argument('--alpha',type=float,default=0.6)
        p.add_argument('--agg_op',type=str,default='max')
        p.add_argument('--mol_FP',type=str,default='ss')
    elif dataset=='Tox21':
        p.add_argument('--dataset', type=str,default='BACE')
        p.add_argument('--seed', type=int, default=0)
        p.add_argument('--atom_in_dim', type=int, default=37)
        p.add_argument('--bond_in_dim', type=int, default=13)
        p.add_argument('--ss_node_in_dim', type=int, default=50)
        p.add_argument('--ss_edge_in_dim', type=int, default=37)
        p.add_argument('--mol_in_dim', type=int, default=167)
        p.add_argument('--learning_rate', type=int, default=5e-3)
        p.add_argument('--epoch', type=int, default=150)
        p.add_argument('--batch_size', type=int, default=128)
        p.add_argument('--num_neurons', type=list, default=[512])
        p.add_argument('--input_norm', type=str, default='layer')
        p.add_argument('--drop_rate', type=float, default=0.4)
        p.add_argument('--hid_dim', type=int, default=96)
        p.add_argument('--device', type=str, default='cuda:0')
        p.add_argument('--dist',type=float,default=0.16)
        p.add_argument('--split_ratio',type=list,default=[0.8,0.1,0.1])
        p.add_argument('--folds',type=int,default=10)
        p.add_argument('--n_jobs',type=int,default=40)
        p.add_argument('--resdual',type=bool,default=False)
        p.add_argument('--shuffle',type=bool,default=False)
        p.add_argument('--attention',type=bool,default=False)
        p.add_argument('--step',type=int,default=4)
        p.add_argument('--alpha',type=float,default=0.4)
        p.add_argument('--agg_op',type=str,default='max')
        p.add_argument('--mol_FP',type=str,default='ss')
    elif dataset=='ClinTox':
        p.add_argument('--dataset', type=str,default='ClinTox')
        p.add_argument('--seed', type=int, default=0)
        p.add_argument('--atom_in_dim', type=int, default=37)
        p.add_argument('--bond_in_dim', type=int, default=13)
        p.add_argument('--ss_node_in_dim', type=int, default=50)
        p.add_argument('--ss_edge_in_dim', type=int, default=37)
        p.add_argument('--mol_in_dim', type=int, default=167)
        p.add_argument('--learning_rate', type=int, default=5e-3)
        p.add_argument('--epoch', type=int, default=150)
        p.add_argument('--batch_size', type=int, default=150)
        p.add_argument('--num_neurons', type=list, default=[512])
        p.add_argument('--input_norm', type=str, default='layer')
        p.add_argument('--drop_rate', type=float, default=0.4)
        p.add_argument('--hid_dim', type=int, default=96)
        p.add_argument('--device', type=str, default='cuda:0')
        p.add_argument('--dist',type=float,default=0.16)
        p.add_argument('--split_ratio',type=list,default=[0.8,0.1,0.1])
        p.add_argument('--folds',type=int,default=10)
        p.add_argument('--n_jobs',type=int,default=40)
        p.add_argument('--resdual',type=bool,default=False)
        p.add_argument('--shuffle',type=bool,default=False)
        p.add_argument('--attention',type=bool,default=True)
        p.add_argument('--step',type=int,default=4)
        p.add_argument('--alpha',type=float,default=0.4)
        p.add_argument('--agg_op',type=str,default='max')
        p.add_argument('--mol_FP',type=str,default='ss')
    elif dataset=='ESOL':
        p.add_argument('--dataset', type=str,default='ESOL')
        p.add_argument('--seed', type=int, default=0)
        p.add_argument('--atom_in_dim', type=int, default=37)
        p.add_argument('--bond_in_dim', type=int, default=13)
        p.add_argument('--ss_node_in_dim', type=int, default=50)
        p.add_argument('--ss_edge_in_dim', type=int, default=37)
        p.add_argument('--mol_in_dim', type=int, default=167)
        p.add_argument('--learning_rate', type=int, default=5e-3)
        p.add_argument('--epoch', type=int, default=200)
        p.add_argument('--batch_size', type=int, default=200)
        p.add_argument('--num_neurons', type=list, default=[512])
        p.add_argument('--input_norm', type=str, default='layer')
        p.add_argument('--drop_rate', type=float, default=0.02)
        p.add_argument('--hid_dim', type=int, default=150)
        p.add_argument('--device', type=str, default='cuda:0')
        p.add_argument('--dist',type=float,default=0.005)
        p.add_argument('--split_ratio',type=list,default=[0.8,0.1,0.1])
        p.add_argument('--folds',type=int,default=10)
        p.add_argument('--n_jobs',type=int,default=40)
        p.add_argument('--resdual',type=bool,default=False)
        p.add_argument('--shuffle',type=bool,default=False)
        p.add_argument('--attention',type=bool,default=True)
        p.add_argument('--step',type=int,default=4)
        p.add_argument('--alpha',type=float,default=0.5)
        p.add_argument('--agg_op',type=str,default='mean')
        p.add_argument('--mol_FP',type=str,default='both')
    elif dataset=='FreeSolv':
        p.add_argument('--dataset', type=str,default='FreeSolv')
        p.add_argument('--seed', type=int, default=0)
        p.add_argument('--atom_in_dim', type=int, default=37)
        p.add_argument('--bond_in_dim', type=int, default=13)
        p.add_argument('--ss_node_in_dim', type=int, default=50)
        p.add_argument('--ss_edge_in_dim', type=int, default=37)
        p.add_argument('--mol_in_dim', type=int, default=167)
        p.add_argument('--learning_rate', type=int, default=5e-3)
        p.add_argument('--epoch', type=int, default=300)
        p.add_argument('--batch_size', type=int, default=128)
        p.add_argument('--num_neurons', type=list, default=[512])
        p.add_argument('--input_norm', type=str, default='layer')
        p.add_argument('--drop_rate', type=float, default=0.01)
        p.add_argument('--hid_dim', type=int, default=150)
        p.add_argument('--device', type=str, default='cuda:0')
        p.add_argument('--dist',type=float,default=0.005)
        p.add_argument('--split_ratio',type=list,default=[0.8,0.1,0.1])
        p.add_argument('--folds',type=int,default=10)
        p.add_argument('--n_jobs',type=int,default=40)
        p.add_argument('--resdual',type=bool,default=False)
        p.add_argument('--shuffle',type=bool,default=False)
        p.add_argument('--attention',type=bool,default=False)
        p.add_argument('--step',type=int,default=1)
        p.add_argument('--alpha',type=float,default=0.2)
        p.add_argument('--agg_op',type=str,default='max')
        p.add_argument('--mol_FP',type=str,default='both')
    elif dataset=='Lipophilicity':
        p.add_argument('--dataset', type=str,default='Lipophilicity')
        p.add_argument('--seed', type=int, default=0)
        p.add_argument('--atom_in_dim', type=int, default=37)
        p.add_argument('--bond_in_dim', type=int, default=13)
        p.add_argument('--ss_node_in_dim', type=int, default=50)
        p.add_argument('--ss_edge_in_dim', type=int, default=37)
        p.add_argument('--mol_in_dim', type=int, default=167)
        p.add_argument('--learning_rate', type=int, default=1e-3)
        p.add_argument('--epoch', type=int, default=200)
        p.add_argument('--batch_size', type=int, default=150)
        p.add_argument('--num_neurons', type=list, default=[512])
        p.add_argument('--input_norm', type=str, default='layer')
        p.add_argument('--drop_rate', type=float, default=0.02)
        p.add_argument('--hid_dim', type=int, default=150)
        p.add_argument('--device', type=str, default='cuda:0')
        p.add_argument('--dist',type=float,default=0.005)
        p.add_argument('--split_ratio',type=list,default=[0.8,0.1,0.1])
        p.add_argument('--folds',type=int,default=10)
        p.add_argument('--n_jobs',type=int,default=40)
        p.add_argument('--resdual',type=bool,default=True)
        p.add_argument('--shuffle',type=bool,default=False)
        p.add_argument('--attention',type=bool,default=True)
        p.add_argument('--step',type=int,default=2)
        p.add_argument('--alpha',type=float,default=0.6)
        p.add_argument('--agg_op',type=str,default='mean')
        p.add_argument('--mol_FP',type=str,default='ss')
    
    args = p.parse_args()
    return args
